name: Debug Jest Permissions

on: push

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install
      - run: ls -l node_modules/.bin # List the contents of the .bin directory
      - run: file node_modules/.bin/jest # Check the file type and permissions of jest
